
name: VSCode Extension Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: sudo apt-get update
    - run: sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb libgtk-3-0 libgbm1
    - run: sudo cp .github/workflows/xvfb.init /etc/init.d/xvfb
    - run: sudo chmod +x /etc/init.d/xvfb
    - run: sudo update-rc.d xvfb defaults
    - run: sudo service xvfb start
    - run: yarn install
    - run: yarn test

# jobs:
#   build:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [macos-latest, ubuntu-latest, windows-latest]
#         node: [12.14.1] # matches Electron 9.x
#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - run: yarn install
#     - run: yarn test
